services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    environment:
      TZ: ${TZ:-Asia/Shanghai}
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    stop_grace_period: 30s
